#!/usr/bin/env python3
"""Write firmware/rtc_stamp.h from host local time (flash.sh / sync.sh)."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "firmware" / "barista_monitor" / "rtc_stamp.h"

now = datetime.now()
content = f"""// Auto-generated by scripts/write_rtc_stamp.py - do not edit.
#pragma once
#define RTC_STAMP_YEAR {now.year}
#define RTC_STAMP_MONTH {now.month}
#define RTC_STAMP_DAY {now.day}
#define RTC_STAMP_HOUR {now.hour}
#define RTC_STAMP_MIN {now.minute}
#define RTC_STAMP_SEC {now.second}
"""

OUT.write_text(content, encoding="ascii")
print(f"rtc_stamp.h -> {now.strftime('%Y-%m-%d %H:%M:%S')} (Lokalzeit)")